pipeline {
   agent { label 'docker-efs-test'}

   stages {
      stage('Run Docker') {
         steps {
            sh 'docker info'
            sh 'mvn -v'
            sh 'mvn help:effective-settings'
         }
      }

       stage('pwd') {
               steps {
                   sh 'pwd'
                   sh 'mvn test'
                   sh 'mvn install'
                }
       }



   }
}
